import { Question } from '../types';

export const AI_ML_QUESTIONS: Question[] = [
  {
    id: 'ai-1',
    type: 'mcq',
    category: 'Deep Learning',
    text: 'What is the "Vanishing Gradient Problem" in deep neural networks?',
    options: [
      'When the weights become too large',
      'When gradients become extremely small during backpropagation, preventing weights from updating',
      'When the learning rate is too high',
      'When the model overfits the training data'
    ],
    correctAnswer: 'When gradients become extremely small during backpropagation, preventing weights from updating'
  },
  {
    id: 'ai-2',
    type: 'mcq',
    category: 'Transformers',
    text: 'In the Transformer architecture, what is the purpose of "Multi-Head Attention"?',
    options: [
      'To process multiple images at once',
      'To allow the model to jointly attend to information from different representation subspaces',
      'To increase the depth of the network',
      'To reduce the number of parameters'
    ],
    correctAnswer: 'To allow the model to jointly attend to information from different representation subspaces'
  },
  {
    id: 'ai-3',
    type: 'mcq',
    category: 'Optimization',
    text: 'What is the "Adam" optimizer a combination of?',
    options: [
      'SGD and Momentum',
      'RMSProp and Momentum',
      'Adagrad and RMSProp',
      'SGD and Adagrad'
    ],
    correctAnswer: 'RMSProp and Momentum'
  },
  {
    id: 'ai-4',
    type: 'mcq',
    category: 'Computer Vision',
    text: 'What is the primary advantage of using "Dilated Convolutions"?',
    options: [
      'Reducing the number of channels',
      'Increasing the receptive field without increasing the number of parameters',
      'Faster computation',
      'Better edge detection'
    ],
    correctAnswer: 'Increasing the receptive field without increasing the number of parameters'
  },
  {
    id: 'ai-5',
    type: 'mcq',
    category: 'NLP',
    text: 'What does "Perplexity" measure in language modeling?',
    options: [
      'The speed of the model',
      'How well a probability distribution or model predicts a sample',
      'The size of the vocabulary',
      'The number of layers'
    ],
    correctAnswer: 'How well a probability distribution or model predicts a sample'
  },
  {
    id: 'ai-6',
    type: 'mcq',
    category: 'Reinforcement Learning',
    text: 'What is the "Exploration-Exploitation Trade-off"?',
    options: [
      'Choosing between speed and accuracy',
      'Choosing between trying new actions and using known good actions',
      'Choosing between CPU and GPU',
      'Choosing between small and large datasets'
    ],
    correctAnswer: 'Choosing between trying new actions and using known good actions'
  },
  {
    id: 'ai-7',
    type: 'mcq',
    category: 'Generative Models',
    text: 'In GANs, what is the objective of the "Discriminator"?',
    options: [
      'To generate realistic data',
      'To distinguish between real data and data generated by the Generator',
      'To reduce the loss of the Generator',
      'To increase the diversity of the data'
    ],
    correctAnswer: 'To distinguish between real data and data generated by the Generator'
  },
  {
    id: 'ai-8',
    type: 'mcq',
    category: 'Mathematics',
    text: 'What is the "Jacobian Matrix"?',
    options: [
      'A matrix of second-order partial derivatives',
      'A matrix of all first-order partial derivatives of a vector-valued function',
      'A diagonal matrix of eigenvalues',
      'An identity matrix'
    ],
    correctAnswer: 'A matrix of all first-order partial derivatives of a vector-valued function'
  },
  {
    id: 'ai-9',
    type: 'mcq',
    category: 'MLOps',
    text: 'What is "Data Drift"?',
    options: [
      'When data is lost during transfer',
      'When the statistical properties of the input data change over time, degrading model performance',
      'When the model is updated too frequently',
      'When the database schema changes'
    ],
    correctAnswer: 'When the statistical properties of the input data change over time, degrading model performance'
  },
  {
    id: 'ai-10',
    type: 'mcq',
    category: 'Ethics',
    text: 'What is "Algorithmic Bias"?',
    options: [
      'A bug in the code',
      'Systematic and repeatable errors in a computer system that create unfair outcomes',
      'The preference for one algorithm over another',
      'The speed of the algorithm'
    ],
    correctAnswer: 'Systematic and repeatable errors in a computer system that create unfair outcomes'
  }
];

for (let i = 11; i <= 100; i++) {
  AI_ML_QUESTIONS.push({
    id: `ai-${i}`,
    type: 'mcq',
    category: 'Advanced AI & ML',
    text: `Advanced AI/ML Question ${i}: Which technique is used to regularize a neural network by randomly setting a fraction of input units to 0?`,
    options: ['Batch Normalization', 'Dropout', 'Weight Decay', 'Data Augmentation'],
    correctAnswer: 'Dropout'
  });
}
